name: Deploy

on:
  push:
    branches:
      - master

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Decrypt firebaseAuth secrets
        run: ./.github/scripts/decrypt_secret.sh
        env:
          DECRYPT_PASSPHRASE: ${{ secrets.DECRYPT_PASSPHRASE }}
      - name: Test printing your secret (Remove this step in production)
        run: ls -al src/utils
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jana19/treelative-api:prod
      - name: Redeploy on Portainer
        uses: wei/curl@master
        with:
          args: -X POST ${{ secrets.DEPLOY_API }}
